#include "rf/commands.h"

#include <stddef.h>

_Static_assert(
    PHASE_LOOKUP_2_4_GHZ_STATE_COUNT == PHASE_STATE_COUNT,
    "phase enum mapping must contain every CAN phase state");

/*
 * Convert the sequential CAN stateWordTableIndex to its nonsequential enum value.
 * A direct cast from the index to optimizedPhaseState_e is incorrect.
 */
static const optimizedPhaseState_e optimizedPhaseStateByIndex[
    PHASE_LOOKUP_2_4_GHZ_STATE_COUNT] = {
    OPTIMIZED_STATE_0, OPTIMIZED_STATE_1, OPTIMIZED_STATE_2, OPTIMIZED_STATE_3,
    OPTIMIZED_STATE_4, OPTIMIZED_STATE_5, OPTIMIZED_STATE_6, OPTIMIZED_STATE_7,
    OPTIMIZED_STATE_8, OPTIMIZED_STATE_9, OPTIMIZED_STATE_10, OPTIMIZED_STATE_11,
    OPTIMIZED_STATE_12, OPTIMIZED_STATE_13, OPTIMIZED_STATE_14, OPTIMIZED_STATE_15,
    OPTIMIZED_STATE_16, OPTIMIZED_STATE_17, OPTIMIZED_STATE_18, OPTIMIZED_STATE_19,
    OPTIMIZED_STATE_20, OPTIMIZED_STATE_21, OPTIMIZED_STATE_22, OPTIMIZED_STATE_23,
    OPTIMIZED_STATE_24, OPTIMIZED_STATE_25, OPTIMIZED_STATE_26, OPTIMIZED_STATE_27,
    OPTIMIZED_STATE_28, OPTIMIZED_STATE_29, OPTIMIZED_STATE_30, OPTIMIZED_STATE_31,
    OPTIMIZED_STATE_32, OPTIMIZED_STATE_33, OPTIMIZED_STATE_34, OPTIMIZED_STATE_35,
    OPTIMIZED_STATE_36, OPTIMIZED_STATE_37, OPTIMIZED_STATE_38, OPTIMIZED_STATE_39,
    OPTIMIZED_STATE_40, OPTIMIZED_STATE_41, OPTIMIZED_STATE_42, OPTIMIZED_STATE_43,
    OPTIMIZED_STATE_44, OPTIMIZED_STATE_45, OPTIMIZED_STATE_46, OPTIMIZED_STATE_47,
    OPTIMIZED_STATE_48, OPTIMIZED_STATE_49, OPTIMIZED_STATE_50, OPTIMIZED_STATE_51,
    OPTIMIZED_STATE_52, OPTIMIZED_STATE_53, OPTIMIZED_STATE_54, OPTIMIZED_STATE_55,
    OPTIMIZED_STATE_56, OPTIMIZED_STATE_57, OPTIMIZED_STATE_58, OPTIMIZED_STATE_59,
    OPTIMIZED_STATE_60, OPTIMIZED_STATE_61, OPTIMIZED_STATE_62, OPTIMIZED_STATE_63,
    OPTIMIZED_STATE_64, OPTIMIZED_STATE_65, OPTIMIZED_STATE_66, OPTIMIZED_STATE_67,
    OPTIMIZED_STATE_68, OPTIMIZED_STATE_69, OPTIMIZED_STATE_70, OPTIMIZED_STATE_71,
    OPTIMIZED_STATE_72, OPTIMIZED_STATE_73, OPTIMIZED_STATE_74, OPTIMIZED_STATE_75,
    OPTIMIZED_STATE_76, OPTIMIZED_STATE_77, OPTIMIZED_STATE_78, OPTIMIZED_STATE_79,
    OPTIMIZED_STATE_80, OPTIMIZED_STATE_81, OPTIMIZED_STATE_82, OPTIMIZED_STATE_83,
    OPTIMIZED_STATE_84, OPTIMIZED_STATE_85, OPTIMIZED_STATE_86, OPTIMIZED_STATE_87,
    OPTIMIZED_STATE_88, OPTIMIZED_STATE_89, OPTIMIZED_STATE_90, OPTIMIZED_STATE_91,
    OPTIMIZED_STATE_92, OPTIMIZED_STATE_93, OPTIMIZED_STATE_94, OPTIMIZED_STATE_95,
    OPTIMIZED_STATE_96, OPTIMIZED_STATE_97, OPTIMIZED_STATE_98, OPTIMIZED_STATE_99,
    OPTIMIZED_STATE_100, OPTIMIZED_STATE_101, OPTIMIZED_STATE_102, OPTIMIZED_STATE_103,
    OPTIMIZED_STATE_104, OPTIMIZED_STATE_105, OPTIMIZED_STATE_106, OPTIMIZED_STATE_107,
    OPTIMIZED_STATE_108, OPTIMIZED_STATE_109, OPTIMIZED_STATE_110, OPTIMIZED_STATE_111,
    OPTIMIZED_STATE_112, OPTIMIZED_STATE_113, OPTIMIZED_STATE_114, OPTIMIZED_STATE_115,
    OPTIMIZED_STATE_116, OPTIMIZED_STATE_117, OPTIMIZED_STATE_118, OPTIMIZED_STATE_119,
    OPTIMIZED_STATE_120, OPTIMIZED_STATE_121, OPTIMIZED_STATE_122, OPTIMIZED_STATE_123,
    OPTIMIZED_STATE_124, OPTIMIZED_STATE_125, OPTIMIZED_STATE_126, OPTIMIZED_STATE_127,
    OPTIMIZED_STATE_128, OPTIMIZED_STATE_129, OPTIMIZED_STATE_130, OPTIMIZED_STATE_131,
    OPTIMIZED_STATE_132, OPTIMIZED_STATE_133, OPTIMIZED_STATE_134, OPTIMIZED_STATE_135,
    OPTIMIZED_STATE_136, OPTIMIZED_STATE_137, OPTIMIZED_STATE_138, OPTIMIZED_STATE_139,
    OPTIMIZED_STATE_140, OPTIMIZED_STATE_141, OPTIMIZED_STATE_142, OPTIMIZED_STATE_143,
    OPTIMIZED_STATE_144, OPTIMIZED_STATE_145, OPTIMIZED_STATE_146, OPTIMIZED_STATE_147,
    OPTIMIZED_STATE_148, OPTIMIZED_STATE_149, OPTIMIZED_STATE_150, OPTIMIZED_STATE_151,
    OPTIMIZED_STATE_152, OPTIMIZED_STATE_153, OPTIMIZED_STATE_154, OPTIMIZED_STATE_155,
    OPTIMIZED_STATE_156, OPTIMIZED_STATE_157, OPTIMIZED_STATE_158, OPTIMIZED_STATE_159,
    OPTIMIZED_STATE_160, OPTIMIZED_STATE_161, OPTIMIZED_STATE_162, OPTIMIZED_STATE_163,
    OPTIMIZED_STATE_164, OPTIMIZED_STATE_165, OPTIMIZED_STATE_166, OPTIMIZED_STATE_167,
    OPTIMIZED_STATE_168, OPTIMIZED_STATE_169, OPTIMIZED_STATE_170, OPTIMIZED_STATE_171,
    OPTIMIZED_STATE_172, OPTIMIZED_STATE_173, OPTIMIZED_STATE_174, OPTIMIZED_STATE_175,
    OPTIMIZED_STATE_176, OPTIMIZED_STATE_177, OPTIMIZED_STATE_178, OPTIMIZED_STATE_179,
    OPTIMIZED_STATE_180, OPTIMIZED_STATE_181, OPTIMIZED_STATE_182, OPTIMIZED_STATE_183,
    OPTIMIZED_STATE_184, OPTIMIZED_STATE_185, OPTIMIZED_STATE_186, OPTIMIZED_STATE_187,
    OPTIMIZED_STATE_188, OPTIMIZED_STATE_189, OPTIMIZED_STATE_190, OPTIMIZED_STATE_191,
    OPTIMIZED_STATE_192, OPTIMIZED_STATE_193, OPTIMIZED_STATE_194, OPTIMIZED_STATE_195,
    OPTIMIZED_STATE_196, OPTIMIZED_STATE_197, OPTIMIZED_STATE_198, OPTIMIZED_STATE_199,
    OPTIMIZED_STATE_200, OPTIMIZED_STATE_201, OPTIMIZED_STATE_202, OPTIMIZED_STATE_203,
    OPTIMIZED_STATE_204, OPTIMIZED_STATE_205, OPTIMIZED_STATE_206, OPTIMIZED_STATE_207,
    OPTIMIZED_STATE_208, OPTIMIZED_STATE_209, OPTIMIZED_STATE_210, OPTIMIZED_STATE_211,
    OPTIMIZED_STATE_212, OPTIMIZED_STATE_213, OPTIMIZED_STATE_214, OPTIMIZED_STATE_215,
    OPTIMIZED_STATE_216, OPTIMIZED_STATE_217, OPTIMIZED_STATE_218, OPTIMIZED_STATE_219,
    OPTIMIZED_STATE_220, OPTIMIZED_STATE_221, OPTIMIZED_STATE_222, OPTIMIZED_STATE_223,
    OPTIMIZED_STATE_224, OPTIMIZED_STATE_225, OPTIMIZED_STATE_226, OPTIMIZED_STATE_227,
    OPTIMIZED_STATE_228, OPTIMIZED_STATE_229, OPTIMIZED_STATE_230, OPTIMIZED_STATE_231,
    OPTIMIZED_STATE_232, OPTIMIZED_STATE_233, OPTIMIZED_STATE_234, OPTIMIZED_STATE_235,
    OPTIMIZED_STATE_236, OPTIMIZED_STATE_237, OPTIMIZED_STATE_238, OPTIMIZED_STATE_239,
    OPTIMIZED_STATE_240, OPTIMIZED_STATE_241, OPTIMIZED_STATE_242, OPTIMIZED_STATE_243,
    OPTIMIZED_STATE_244, OPTIMIZED_STATE_245, OPTIMIZED_STATE_246, OPTIMIZED_STATE_247,
    OPTIMIZED_STATE_248, OPTIMIZED_STATE_249, OPTIMIZED_STATE_250, OPTIMIZED_STATE_251,
    OPTIMIZED_STATE_252, OPTIMIZED_STATE_253, OPTIMIZED_STATE_254, OPTIMIZED_STATE_255,
};

// The phase word and address need their bit order reversed before packing.
uint16_t reverseBits(uint16_t word, uint8_t numBits)
{
    uint16_t reversed = 0u;

    for (uint8_t i = 0u; i < numBits; ++i) {
        reversed = (uint16_t)((reversed << 1u) | (word & 0x1u));
        word >>= 1u;
    }

    return reversed;
}

optimizedPhaseState_e GetOptimizedPhaseState(uint8_t stateWordTableIndex)
{
    return optimizedPhaseStateByIndex[stateWordTableIndex];
}

uint16_t MakePSCommand(optimizedPhaseState_e phaseState, uint8_t unitAddressWord)
{
    // [reversedStateWord][optBit][reversedAddress]
    const uint16_t stateWord = (uint16_t)phaseState;
    const bool optBit = (stateWord & PHASE_CONTROL_WORD_OPTION_MASK) != 0u;
    uint16_t stateWordMasked = stateWord & PHASE_CONTROL_WORD_DATA_MASK;

    stateWordMasked = reverseBits(stateWordMasked, PHASE_STATE_BITS);
    unitAddressWord = (uint8_t)reverseBits(unitAddressWord, PHASE_UNIT_ADDRESS_BITS);

    return (uint16_t)(
        ((stateWordMasked & 0xffu) << PHASE_COMMAND_PHASE_SHIFT)
        | ((uint16_t)optBit << PHASE_COMMAND_OPTION_SHIFT)
        | (unitAddressWord & PHASE_COMMAND_ADDRESS_MASK));
}

bool phase_state_from_millidegrees(
    uint32_t requested_shift_millidegrees,
    uint8_t *phase_state)
{
    if (phase_state == NULL
        || requested_shift_millidegrees > PHASE_FULL_TURN_MILLIDEGREES) {
        return false;
    }

    const uint64_t scaled =
        ((uint64_t)requested_shift_millidegrees * PHASE_STATE_COUNT)
        + (PHASE_FULL_TURN_MILLIDEGREES / 2u);
    *phase_state = (uint8_t)((scaled / PHASE_FULL_TURN_MILLIDEGREES) & 0xffu);
    return true;
}

bool MakeVGACommand(uint8_t attenuationDb, uint8_t *command)
{
    if ((command == NULL) || (attenuationDb > VGA_MAX_ATTENUATION_DB)) {
        return false;
    }

    *command = (uint8_t)(attenuationDb << VGA_COMMAND_ATTENUATION_SHIFT);
    return true;
}
