"""Generate protocol/generated/protocol_vectors.h from protocol/v3.0-vectors.toml.

Run `--check` in CI to fail if the committed header is stale.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

import tomllib

ROOT = Path(__file__).resolve().parent.parent
TOML = ROOT / "protocol" / "v3.0-vectors.toml"
OUT = ROOT / "protocol" / "generated" / "protocol_vectors.h"

HEADER = """/*
 * Generated by tools/generate-protocol-vectors.py from protocol/v3.0-vectors.toml.
 * Do not edit by hand. Run `python3 tools/generate-protocol-vectors.py` to regenerate.
 */
#ifndef PROTOCOL_VECTORS_H
#define PROTOCOL_VECTORS_H

#include <stdbool.h>
#include <stdint.h>

typedef struct protocol_id_vector {{
    const char *name;
    uint8_t type;
    uint8_t destination;
    uint8_t source;
    uint16_t sequence;
    uint32_t extended_id;
}} protocol_id_vector_t;

typedef struct protocol_command_vector {{
    const char *name;
    uint8_t type;
    uint8_t destination;
    uint8_t source;
    uint16_t sequence;
    uint8_t data[8];
    uint8_t length;
    bool valid;
    uint8_t result;
}} protocol_command_vector_t;

{id_vectors}

{command_vectors}

#endif /* PROTOCOL_VECTORS_H */
"""


def _c_bytes(data: list[int]) -> str:
    return "{" + ", ".join(f"0x{b:02x}u" for b in data) + "}"


def render(data: dict) -> str:
    id_vectors = (
        "static const protocol_id_vector_t PROTOCOL_ID_VECTORS[] = {\n"
        + "\n".join(
            f'    {{ "{v["name"]}", {v["type"]}u, {v["destination"]}u, '
            f"{v['source']}u, {v['sequence']}u, 0x{v['extended_id']:08X}u }},"
            for v in data["id_vectors"]
        )
        + "\n};\n"
        + f"static const uint32_t PROTOCOL_ID_VECTORS_COUNT = {len(data['id_vectors'])}u;\n"
    )

    command_vectors = (
        "static const protocol_command_vector_t PROTOCOL_COMMAND_VECTORS[] = {\n"
        + "\n".join(
            f'    {{ "{v["name"]}", {v["type"]}u, {v["destination"]}u, '
            f"{v['source']}u, {v['sequence']}u, "
            f"{_c_bytes(v['data'] + [0] * (8 - len(v['data'])))}, "
            f"{len(v['data'])}u, "
            f"{'true' if v['valid'] else 'false'}, "
            f"{v.get('result', 0)}u }},"
            for v in data["commands"]
        )
        + "\n};\n"
        + f"static const uint32_t PROTOCOL_COMMAND_VECTORS_COUNT = {len(data['commands'])}u;\n"
    )

    return HEADER.format(id_vectors=id_vectors, command_vectors=command_vectors)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the generated header is up to date; exit nonzero if not",
    )
    args = parser.parse_args()

    data = tomllib.loads(TOML.read_text(encoding="utf-8"))
    rendered = render(data)

    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != rendered:
            print(
                "protocol_vectors.h is stale; run generate-protocol-vectors.py",
                file=sys.stderr,
            )
            return 1
        print("protocol_vectors.h is up to date")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    digest = hashlib.sha256(rendered.encode()).hexdigest()[:12]
    print(
        f"wrote {OUT} ({len(data['id_vectors'])} id, "
        f"{len(data['commands'])} command vectors, sha256={digest})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
